class Surah {
  final int number;
  final String name;
  final String translation;
  final String type;
  final int verses;
  final String arabic;
  final int startPage;

  const Surah({
    required this.number,
    required this.name,
    required this.translation,
    required this.type,
    required this.verses,
    required this.arabic,
    required this.startPage,
  });

  String get startImage => startPage.toString().padLeft(3, '0') + ".webp";
}

final List<Surah> surahs = const [
  Surah(number: 1, name: "Al-Fatihah", translation: "The Opener", type: "Makki", verses: 7, arabic: "الفاتحة", startPage: 1),
  Surah(number: 2, name: "Al-Baqarah", translation: "The Cow", type: "Madani", verses: 286, arabic: "البقرة", startPage: 2),
  Surah(number: 3, name: "Al-‘Imran", translation: "Family of Imran", type: "Madani", verses: 200, arabic: "آل عمران", startPage: 50),
  Surah(number: 4, name: "An-Nisa", translation: "The Women", type: "Madani", verses: 176, arabic: "النساء", startPage: 77),
  Surah(number: 5, name: "Al-Ma'idah", translation: "The Table Spread", type: "Madani", verses: 120, arabic: "المائدة", startPage: 106),
  Surah(number: 6, name: "Al-An'am", translation: "The Cattle", type: "Makki", verses: 165, arabic: "الأنعام", startPage: 128),
  Surah(number: 7, name: "Al-A'raf", translation: "The Heights", type: "Makki", verses: 206, arabic: "الأعراف", startPage: 151),
  Surah(number: 8, name: "Al-Anfal", translation: "The Spoils of War", type: "Madani", verses: 75, arabic: "الأنفال", startPage: 177),
  Surah(number: 9, name: "At-Tawbah", translation: "The Repentance", type: "Madani", verses: 129, arabic: "التوبة", startPage: 187),
  Surah(number: 10, name: "Yunus", translation: "Jonah", type: "Makki", verses: 109, arabic: "يونس", startPage: 208),
  Surah(number: 11, name: "Hud", translation: "Hud", type: "Makki", verses: 123, arabic: "هود", startPage: 221),
  Surah(number: 12, name: "Yusuf", translation: "Joseph", type: "Makki", verses: 111, arabic: "يوسف", startPage: 235),
  Surah(number: 13, name: "Ar-Ra'd", translation: "The Thunder", type: "Madani", verses: 43, arabic: "الرعد", startPage: 249),
  Surah(number: 14, name: "Ibrahim", translation: "Abraham", type: "Makki", verses: 52, arabic: "ابراهيم", startPage: 255),
  Surah(number: 15, name: "Al-Hijr", translation: "The Rocky Tract", type: "Makki", verses: 99, arabic: "الحجر", startPage: 262),
  Surah(number: 16, name: "An-Nahl", translation: "The Bee", type: "Makki", verses: 128, arabic: "النحل", startPage: 267),
  Surah(number: 17, name: "Al-Isra", translation: "The Night Journey", type: "Makki", verses: 111, arabic: "الإسراء", startPage: 282),
  Surah(number: 18, name: "Al-Kahf", translation: "The Cave", type: "Makki", verses: 110, arabic: "الكهف", startPage: 293),
  Surah(number: 19, name: "Maryam", translation: "Mary", type: "Makki", verses: 98, arabic: "مريم", startPage: 305),
  Surah(number: 20, name: "Taha", translation: "Ta-Ha", type: "Makki", verses: 135, arabic: "طه", startPage: 312),
  Surah(number: 21, name: "Al-Anbiya", translation: "The Prophets", type: "Makki", verses: 112, arabic: "الأنبياء", startPage: 322),
  Surah(number: 22, name: "Al-Hajj", translation: "The Pilgrimage", type: "Madani", verses: 78, arabic: "الحج", startPage: 332),
  Surah(number: 23, name: "Al-Mu'minun", translation: "The Believers", type: "Makki", verses: 118, arabic: "المؤمنون", startPage: 342),
  Surah(number: 24, name: "An-Nur", translation: "The Light", type: "Madani", verses: 64, arabic: "النور", startPage: 350),
  Surah(number: 25, name: "Al-Furqan", translation: "The Criterion", type: "Makki", verses: 77, arabic: "الفرقان", startPage: 359),
  Surah(number: 26, name: "Ash-Shu'ara", translation: "The Poets", type: "Makki", verses: 227, arabic: "الشعراء", startPage: 367),
  Surah(number: 27, name: "An-Naml", translation: "The Ant", type: "Makki", verses: 93, arabic: "النمل", startPage: 377),
  Surah(number: 28, name: "Al-Qasas", translation: "The Stories", type: "Makki", verses: 88, arabic: "القصص", startPage: 385),
  Surah(number: 29, name: "Al-'Ankabut", translation: "The Spider", type: "Makki", verses: 69, arabic: "العنكبوت", startPage: 396),
  Surah(number: 30, name: "Ar-Rum", translation: "The Romans", type: "Makki", verses: 60, arabic: "الروم", startPage: 404),
  Surah(number: 31, name: "Luqman", translation: "Luqman", type: "Makki", verses: 34, arabic: "لقمان", startPage: 411),
  Surah(number: 32, name: "As-Sajdah", translation: "The Prostration", type: "Makki", verses: 30, arabic: "السجدة", startPage: 415),
  Surah(number: 33, name: "Al-Ahzab", translation: "The Confederates", type: "Madani", verses: 73, arabic: "الأحزاب", startPage: 418),
  Surah(number: 34, name: "Saba", translation: "Sheba", type: "Makki", verses: 54, arabic: "سبإ", startPage: 428),
  Surah(number: 35, name: "Fatir", translation: "The Originator", type: "Makki", verses: 45, arabic: "فاطر", startPage: 434),
  Surah(number: 36, name: "Ya-Sin", translation: "Ya Sin", type: "Makki", verses: 83, arabic: "يس", startPage: 440),
  Surah(number: 37, name: "As-Saffat", translation: "Those who set the Ranks", type: "Makki", verses: 182, arabic: "الصافات", startPage: 446),
  Surah(number: 38, name: "Sad", translation: "The Letter Sad", type: "Makki", verses: 88, arabic: "ص", startPage: 453),
  Surah(number: 39, name: "Az-Zumar", translation: "The Troops", type: "Makki", verses: 75, arabic: "الزمر", startPage: 458),
  Surah(number: 40, name: "Ghafir", translation: "The Forgiver", type: "Makki", verses: 85, arabic: "غافر", startPage: 467),
  Surah(number: 41, name: "Fussilat", translation: "Explained in Detail", type: "Makki", verses: 54, arabic: "فصلت", startPage: 477),
  Surah(number: 42, name: "Ash-Shura", translation: "The Consultation", type: "Makki", verses: 53, arabic: "الشورى", startPage: 483),
  Surah(number: 43, name: "Az-Zukhruf", translation: "The Ornaments of Gold", type: "Makki", verses: 89, arabic: "الزخرف", startPage: 489),
  Surah(number: 44, name: "Ad-Dukhan", translation: "The Smoke", type: "Makki", verses: 59, arabic: "الدخان", startPage: 496),
  Surah(number: 45, name: "Al-Jathiyah", translation: "The Crouching", type: "Makki", verses: 37, arabic: "الجاثية", startPage: 499),
  Surah(number: 46, name: "Al-Ahqaf", translation: "The Wind-Curved Sandhills", type: "Makki", verses: 35, arabic: "الأحقاف", startPage: 502),
  Surah(number: 47, name: "Muhammad", translation: "Muhammad", type: "Madani", verses: 38, arabic: "محمد", startPage: 507),
  Surah(number: 48, name: "Al-Fath", translation: "The Victory", type: "Madani", verses: 29, arabic: "الفتح", startPage: 511),
  Surah(number: 49, name: "Al-Hujurat", translation: "The Rooms", type: "Madani", verses: 18, arabic: "الحجرات", startPage: 515),
  Surah(number: 50, name: "Qaf", translation: "The Letter Qaf", type: "Makki", verses: 45, arabic: "ق", startPage: 518),
  Surah(number: 51, name: "Adh-Dhariyat", translation: "The Winnowing Winds", type: "Makki", verses: 60, arabic: "الذاريات", startPage: 520),
  Surah(number: 52, name: "At-Tur", translation: "The Mount", type: "Makki", verses: 49, arabic: "الطور", startPage: 523),
  Surah(number: 53, name: "An-Najm", translation: "The Star", type: "Makki", verses: 62, arabic: "النجم", startPage: 526),
  Surah(number: 54, name: "Al-Qamar", translation: "The Moon", type: "Makki", verses: 55, arabic: "القمر", startPage: 528),
  Surah(number: 55, name: "Ar-Rahman", translation: "The Beneficent", type: "Madani", verses: 78, arabic: "الرحمن", startPage: 531),
  Surah(number: 56, name: "Al-Waqi'ah", translation: "The Inevitable", type: "Makki", verses: 96, arabic: "الواقعة", startPage: 534),
  Surah(number: 57, name: "Al-Hadid", translation: "The Iron", type: "Madani", verses: 29, arabic: "الحديد", startPage: 537),
  Surah(number: 58, name: "Al-Mujadila", translation: "The Pleading Woman", type: "Madani", verses: 22, arabic: "المجادلة", startPage: 542),
  Surah(number: 59, name: "Al-Hashr", translation: "The Exile", type: "Madani", verses: 24, arabic: "الحشر", startPage: 545),
  Surah(number: 60, name: "Al-Mumtahanah", translation: "She that is to be examined", type: "Madani", verses: 13, arabic: "الممتحنة", startPage: 549),
  Surah(number: 61, name: "As-Saff", translation: "The Ranks", type: "Madani", verses: 14, arabic: "الصف", startPage: 551),
  Surah(number: 62, name: "Al-Jumu'ah", translation: "Friday", type: "Madani", verses: 11, arabic: "الجمعة", startPage: 553),
  Surah(number: 63, name: "Al-Munafiqun", translation: "The Hypocrites", type: "Madani", verses: 11, arabic: "المنافقون", startPage: 554),
  Surah(number: 64, name: "At-Taghabun", translation: "Mutual Disillusion", type: "Madani", verses: 18, arabic: "التغابن", startPage: 556),
  Surah(number: 65, name: "At-Talaq", translation: "Divorce", type: "Madani", verses: 12, arabic: "الطلاق", startPage: 558),
  Surah(number: 66, name: "At-Tahrim", translation: "The Prohibition", type: "Madani", verses: 12, arabic: "التحريم", startPage: 560),
  Surah(number: 67, name: "Al-Mulk", translation: "The Sovereignty", type: "Makki", verses: 30, arabic: "الملك", startPage: 562),
  Surah(number: 68, name: "Al-Qalam", translation: "The Pen", type: "Makki", verses: 52, arabic: "القلم", startPage: 564),
  Surah(number: 69, name: "Al-Haqqah", translation: "The Reality", type: "Makki", verses: 52, arabic: "الحاقة", startPage: 566),
  Surah(number: 70, name: "Al-Ma'arij", translation: "The Ascending Stairways", type: "Makki", verses: 44, arabic: "المعارج", startPage: 568),
  Surah(number: 71, name: "Nuh", translation: "Noah", type: "Makki", verses: 28, arabic: "نوح", startPage: 570),
  Surah(number: 72, name: "Al-Jinn", translation: "The Jinn", type: "Makki", verses: 28, arabic: "الجن", startPage: 572),
  Surah(number: 73, name: "Al-Muzzammil", translation: "The Enshrouded One", type: "Makki", verses: 20, arabic: "المزمل", startPage: 574),
  Surah(number: 74, name: "Al-Muddaththir", translation: "The Cloaked One", type: "Makki", verses: 56, arabic: "المدثر", startPage: 575),
  Surah(number: 75, name: "Al-Qiyamah", translation: "The Resurrection", type: "Makki", verses: 40, arabic: "القيامة", startPage: 577),
  Surah(number: 76, name: "Al-Insan", translation: "Man", type: "Madani", verses: 31, arabic: "الانسان", startPage: 578),
  Surah(number: 77, name: "Al-Mursalat", translation: "The Emissaries", type: "Makki", verses: 50, arabic: "المرسلات", startPage: 580),
  Surah(number: 78, name: "An-Naba", translation: "The Tidings", type: "Makki", verses: 40, arabic: "النبإ", startPage: 582),
  Surah(number: 79, name: "An-Nazi'at", translation: "Those who drag forth", type: "Makki", verses: 46, arabic: "النازعات", startPage: 583),
  Surah(number: 80, name: "'Abasa", translation: "He frowned", type: "Makki", verses: 42, arabic: "عبس", startPage: 585),
  Surah(number: 81, name: "At-Takwir", translation: "The Overthrowing", type: "Makki", verses: 29, arabic: "التكوير", startPage: 586),
  Surah(number: 82, name: "Al-Infitar", translation: "The Cleaving", type: "Makki", verses: 19, arabic: "الإنفطار", startPage: 587),
  Surah(number: 83, name: "Al-Mutaffifin", translation: "Defrauding", type: "Makki", verses: 36, arabic: "المطففين", startPage: 587),
  Surah(number: 84, name: "Al-Inshiqaq", translation: "The Sundering", type: "Makki", verses: 25, arabic: "الإنشقاق", startPage: 589),
  Surah(number: 85, name: "Al-Buruj", translation: "The Mansions of the Stars", type: "Makki", verses: 22, arabic: "البروج", startPage: 590),
  Surah(number: 86, name: "At-Tariq", translation: "The Morning Star", type: "Makki", verses: 17, arabic: "الطارق", startPage: 591),
  Surah(number: 87, name: "Al-A'la", translation: "The Most High", type: "Makki", verses: 19, arabic: "الأعلى", startPage: 591),
  Surah(number: 88, name: "Al-Ghashiyah", translation: "The Overwhelming", type: "Makki", verses: 26, arabic: "الغاشية", startPage: 592),
  Surah(number: 89, name: "Al-Fajr", translation: "The Dawn", type: "Makki", verses: 30, arabic: "الفجر", startPage: 593),
  Surah(number: 90, name: "Al-Balad", translation: "The City", type: "Makki", verses: 20, arabic: "البلد", startPage: 594),
  Surah(number: 91, name: "Ash-Shams", translation: "The Sun", type: "Makki", verses: 15, arabic: "الشمس", startPage: 595),
  Surah(number: 92, name: "Al-Layl", translation: "The Night", type: "Makki", verses: 21, arabic: "الليل", startPage: 595),
  Surah(number: 93, name: "Ad-Duha", translation: "The Morning Hours", type: "Makki", verses: 11, arabic: "الضحى", startPage: 596),
  Surah(number: 94, name: "Ash-Sharh", translation: "The Relief", type: "Makki", verses: 8, arabic: "الشرح", startPage: 596),
  Surah(number: 95, name: "At-Tin", translation: "The Fig", type: "Makki", verses: 8, arabic: "التين", startPage: 597),
  Surah(number: 96, name: "Al-'Alaq", translation: "The Clot", type: "Makki", verses: 19, arabic: "العلق", startPage: 597),
  Surah(number: 97, name: "Al-Qadr", translation: "The Power", type: "Makki", verses: 5, arabic: "القدر", startPage: 598),
  Surah(number: 98, name: "Al-Bayyinah", translation: "The Clear Proof", type: "Madani", verses: 8, arabic: "البينة", startPage: 598),
  Surah(number: 99, name: "Az-Zalzalah", translation: "The Earthquake", type: "Madani", verses: 8, arabic: "الزلزلة", startPage: 599),
  Surah(number: 100, name: "Al-'Adiyat", translation: "The Courser", type: "Makki", verses: 11, arabic: "العاديات", startPage: 599),
  Surah(number: 101, name: "Al-Qari'ah", translation: "The Calamity", type: "Makki", verses: 11, arabic: "القارعة", startPage: 600),
  Surah(number: 102, name: "At-Takathur", translation: "The Rivalry in world increase", type: "Makki", verses: 8, arabic: "التكاثر", startPage: 600),
  Surah(number: 103, name: "Al-'Asr", translation: "The Declining Day", type: "Makki", verses: 3, arabic: "العصر", startPage: 601),
  Surah(number: 104, name: "Al-Humazah", translation: "The Traducer", type: "Makki", verses: 9, arabic: "الهمزة", startPage: 601),
  Surah(number: 105, name: "Al-Fil", translation: "The Elephant", type: "Makki", verses: 5, arabic: "الفيل", startPage: 601),
  Surah(number: 106, name: "Quraysh", translation: "Quraysh", type: "Makki", verses: 4, arabic: "قريش", startPage: 602),
  Surah(number: 107, name: "Al-Ma'un", translation: "The Small Kindnesses", type: "Makki", verses: 7, arabic: "الماعون", startPage: 602),
  Surah(number: 108, name: "Al-Kawthar", translation: "The Abundance", type: "Makki", verses: 3, arabic: "الكوثر", startPage: 602),
  Surah(number: 109, name: "Al-Kafirun", translation: "The Disbelievers", type: "Makki", verses: 6, arabic: "الكافرون", startPage: 603),
  Surah(number: 110, name: "An-Nasr", translation: "The Divine Support", type: "Madani", verses: 3, arabic: "النصر", startPage: 603),
  Surah(number: 111, name: "Al-Masad", translation: "The Palm Fiber", type: "Makki", verses: 5, arabic: "المسد", startPage: 603),
  Surah(number: 112, name: "Al-Ikhlas", translation: "The Sincerity", type: "Makki", verses: 4, arabic: "الإخلاص", startPage: 604),
  Surah(number: 113, name: "Al-Falaq", translation: "The Daybreak", type: "Makki", verses: 5, arabic: "الفلق", startPage: 604),
  Surah(number: 114, name: "An-Nas", translation: "Mankind", type: "Makki", verses: 6, arabic: "الناس", startPage: 604),
];
